name: plusfit
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

  firebase_storage: ^7.0.0
  firebase_core: ^0.7.0
  simple_animations: ^2.5.0
  google_fonts: ^1.1.2
  rflutter_alert: ^1.1.0
  mvc_pattern: ^6.0.0
  google_sign_in: ^4.5.9
  firebase_auth: ^0.20.0+1  
  cloud_firestore: 
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+22

  form_field_validator: ^1.0.1
  provider: ^4.3.2+1
  cupertino_icons: ^1.0.1

dev_dependencies:
  


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/superior/
    - assets/inferior/
    - assets/cardio/  
    - assets/exercicios/