name: plusfit
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  google_sign_in: ^4.5.9
  firebase_auth: ^0.20.0+1  
  cloud_firestore: ^0.16.0
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+22

  form_field_validator: ^1.0.1
  provider: ^4.3.2+1
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:


  uses-material-design: true


  assets:
    - assets/Plusfit_logo.png
    - assets/main_menu_background.png
    - assets/sign_up_background.png
    - assets/login_background.png
    - assets/home_background.png
    - assets/back1.png
    - assets/backperfil.png
    - assets/homem.png
    - assets/backedit.png