name: plusfit
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^0.7.0
  simple_animations: ^2.5.0
  google_fonts: ^1.1.2
  rflutter_alert: ^1.1.0
  mvc_pattern: ^6.0.0
  google_sign_in: ^4.5.9
  firebase_auth: ^0.20.0+1  
  cloud_firestore: 
  flutter:
    sdk: flutter
  image_picker: ^0.6.7+22

  form_field_validator: ^1.0.1
  provider: ^4.3.2+1
  cupertino_icons: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:


  uses-material-design: true


  assets:
    - assets/Plusfit_logo.png
    - assets/main_menu_background.png
    - assets/sign_up_background.png
    - assets/login_background.png
    - assets/home_background.png
    - assets/back1.png
    - assets/backperfil.png
    - assets/homem.png
    - assets/backedit.png
    - assets/correndo.jpg
    - assets/signup.jpg
    - assets/icon.png
    - assets/mandar.png
    - assets/superiores.png
    - assets/Inferiores_2.png
    - assets/Cardio_2.png
    - assets/back_treinos.png
    - assets/superior/superiores.jpeg
    - assets/inferior/inferior.jpg
    - assets/cardio.jpg
    - assets/cardio.png
    - assets/superior/costa_biceps.png
    - assets/superior/peitoral_triceps.png
    - assets/superior/peitoral_triceps_abdomen.png
    - assets/inferior/posterior_panturrilha_avancado.jpg
    - assets/inferior/posterior_panturrilha_basico.jpg
    - assets/inferior/posterior_panturrilha_intermediario.jpg
    - assets/cardio/cardio_basico.jpg
    - assets/cardio/cardio_intermediario.jpg
    - assets/cardio/cardio_avancado.jpg
